name: Python Testing
description: A GitHub Action to run Python tests using pytest, generate SVG badges for test results, and optionally commit the badges to the repository.
author: Jason Miller

branding:
  icon: check-circle
  color: green

inputs:
  python-version:
    description: Python version to use for testing. If not specified, uses the default Python available on the runner.
    required: false
    default: '3.x'

  requirements-file:
    description: Path to a requirements file to install before testing. If not specified, only detected test frameworks will be installed.
    required: false
    default: 'requirements.txt'

  pytest-options:
    description: Options to pass to pytest if detected.
    required: false
    default: ''

  commit-badges:
    description: Generate SVG badges for test results and commit them to the repository.
    required: false
    default: 'false'

  badges-directory:
    description: Directory where badge SVG files will be saved (relative to repository root).
    required: false
    default: '.github/badges'

runs:
  using: composite
  steps:
    - name: Setup Python
      id: setup-python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
      continue-on-error: false

    - name: Install pytest
      id: install-pytest
      run: |
        pip install pytest
        echo "✓ Installed pytest" >> $GITHUB_STEP_SUMMARY
      continue-on-error: false
      shell: bash

    - name: Install additional requirements
      run: |
        if [ -f "${{ inputs.requirements-file }}" ]; then
          pip3 install -r "${{ inputs.requirements-file }}"
          echo "✓ Installed requirements from ${{ inputs.requirements-file }}" >> $GITHUB_STEP_SUMMARY
        elif [ "${{ inputs.requirements-file }}" != "" ]; then
          echo "Warning: Requirements file not found: ${{ inputs.requirements-file }}" >> $GITHUB_STEP_SUMMARY
          echo "Skipping additional requirements installation."
        fi
      shell: bash
      if: inputs.requirements-file != ''
      continue-on-error: false

    - name: Run pytest
      run: |
        echo "Running pytest..."
        pytest ${{ inputs.pytest-options }} --verbose --tb=short 2>&1 | tee pytest_output.txt
        echo "PYTEST_EXIT_CODE=${PIPESTATUS[0]}" >> $GITHUB_ENV
      shell: bash
      if: steps.install-pytest.outcome == 'success'
      continue-on-error: true

    - name: Report pytest results
      run: |
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "## pytest :test_tube:" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo '```text' >> $GITHUB_STEP_SUMMARY
        cat pytest_output.txt >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        rm -f pytest_output.txt
      shell: bash
      if: steps.install-pytest.outcome == 'success'
      continue-on-error: false

    - name: Generate SVG badges
      id: generate-badges
      run: |
        mkdir -p "${{ inputs.badges-directory }}"
        
        # Function to create badge
        create_badge() {
          local name=$1
          local status=$2
          local color=$3
          local file=$4
          
          cat > "$file" << 'EOF'
        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="120" height="20">
        <linearGradient id="b" x2="0" y2="100%">
          <stop offset="0" stop-color="#bbb" stop-opacity=".1"/>
          <stop offset="1" stop-opacity=".1"/>
        </linearGradient>
        <clipPath id="a">
          <rect width="120" height="20" rx="3" fill="#fff"/>
        </clipPath>
        <g clip-path="url(#a)">
          <path fill="#555" d="M0 0h60v20H0z"/>
          <path fill="COLOR" d="M60 0h60v20H60z"/>
          <path fill="url(#b)" d="M0 0h120v20H0z"/>
        </g>
        <g fill="#fff" text-anchor="middle" font-family="DejaVu Sans,Verdana,Geneva,sans-serif" font-size="11">
          <text x="30" y="15" fill="#010101" fill-opacity=".3">NAME</text>
          <text x="30" y="14">NAME</text>
          <text x="90" y="15" fill="#010101" fill-opacity=".3">STATUS</text>
          <text x="90" y="14">STATUS</text>
        </g>
        </svg>
        EOF
          sed -i "s/NAME/$name/g; s/STATUS/$status/g; s/COLOR/$color/g" "$file"
        }
        
        # Create badges for detected frameworks
        PYTEST_STATUS="passing"
        PYTEST_COLOR="#4c1"
        [ "${PYTEST_EXIT_CODE:-0}" != "0" ] && PYTEST_STATUS="failing" && PYTEST_COLOR="#e05d44"
        create_badge "pytest" "$PYTEST_STATUS" "$PYTEST_COLOR" "${{ inputs.badges-directory }}/pytest.svg"
        
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "## SVG Badge(s)" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "✓ Generated SVG badges in ${{ inputs.badges-directory }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
      shell: bash
      if: inputs.commit-badges == 'true'
      continue-on-error: false

    - name: Commit badges to repository
      run: |
        if [ "${{ inputs.commit-badges }}" == "true" ]]; then
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          # Add badge files if they exist
          git add "${{ inputs.badges-directory }}/*.svg" 2>/dev/null || true

          echo "## Git" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "✓ Prepared to commit badge files" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          if git diff --staged --quiet || false; then
            echo "No changes to commit" >> $GITHUB_STEP_SUMMARY
          else
            git commit -m "Update test badges [skip ci]"
            if git push || false; then
              echo "✓ Changes committed and pushed to repository" >> $GITHUB_STEP_SUMMARY
            else
              echo "⚠ Warning: Failed to push changes. This may be due to insufficient permissions or a merge conflict." >> $GITHUB_STEP_SUMMARY
              echo "Please ensure the workflow has write permissions to the repository." >> $GITHUB_STEP_SUMMARY
              exit 0
            fi
          fi
        fi
      shell: bash
      if: steps.generate-badges.outcome == 'success' && inputs.commit-badges == 'true'
      continue-on-error: false
